In [9]:
import pandas as pd
import numpy as np


tabela = pd.DataFrame({'Dia': ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo'],
                      'Limpeza': [100, 0, 100, 0, 100, 100, 0],
                      'Comida': [221.60, 375.31, 412, 495.20, 441.53, 245, 164],
                      'Transporte': [150, 100, 125, 300, 275, 525, 75],
                      'Outros': [0, 0, 2310, 500, 0, 0, 820],
                      'Receita': [2200, 2420.50, 3391, 5322, 4898.50, 4200, 3893]})
tabela

       Dia  Limpeza  Comida  Transporte  Outros  Receita
0  Segunda      100  221.60         150       0   2200.0
1    Terça        0  375.31         100       0   2420.5
2   Quarta      100  412.00         125    2310   3391.0
3   Quinta        0  495.20         300     500   5322.0
4    Sexta      100  441.53         275       0   4898.5
5   Sábado      100  245.00         525       0   4200.0
6  Domingo        0  164.00          75     820   3893.0

In [7]:
tabela['Receita'] = tabela['Receita'] * 0.93

tabela['Receita']

0    1902.78000
1    2093.49045
2    2932.87590
3    4602.99780
4    4236.71265
5    3632.58000
6    3367.05570
Name: Receita, dtype: float64

In [10]:
soma_receita = tabela['Receita'].sum()

print("Soma da receita semanal: %.2f"% soma_receita)

Soma dos ganhos da semana: 26325.00

In [16]:
media_receita = tabela['Receita'].mean()

print("Media da receita semanal: %.2f"% media_receita)

Media dos ganhos da semana: 3760.71

In [17]:
print('Soma dos custos da limpeza:',tabela['Limpeza'].sum())

print('Soma dos custos da comida:',tabela['Comida'].sum())

print('Soma dos custos do transporte:',tabela['Transporte'].sum())

print('Soma dos custos de outros:',tabela['Outros'].sum())

Soma dos gastos da limpeza: 400
Soma dos gastos da comida: 2354.64
Soma dos gastos do transporte: 1550
Soma dos gastos de outros: 3630

In [25]:
mediasem = tabela['Limpeza'].sum() + tabela['Comida'].sum() + tabela['Transporte'].sum() + tabela['Outros'].sum() 

print('A media de despesas foi de: {:.2f}'.format(mediasem/4))

A media de despesas foi de: 1983.66

In [30]:
tabela['Lucro'] = tabela['Receita'] - (tabela['Limpeza'] + tabela['Comida'] + tabela['Transporte'] + tabela['Outros'])

melhor_Dia = tabela['Dia'][tabela['Lucro'].idxmax()]

soma_Lucro = tabela['Lucro'].sum()

print(f"Dia mais lucrativo: {melhor_Dia} e seu lucro foi de:{tabela['Lucro'].max():.2f}")
print(f"Lucro total da semana foi:{soma_Lucro:.2f}")

tabela

Dia mais lucrativo: Sexta e seu lucro foi de:4081.97
Lucro total da semana foi:18390.36

       Dia  Limpeza  Comida  Transporte  Outros  Receita    Lucro
0  Segunda      100  221.60         150       0   2200.0  1728.40
1    Terça        0  375.31         100       0   2420.5  1945.19
2   Quarta      100  412.00         125    2310   3391.0   444.00
3   Quinta        0  495.20         300     500   5322.0  4026.80
4    Sexta      100  441.53         275       0   4898.5  4081.97
5   Sábado      100  245.00         525       0   4200.0  3330.00
6  Domingo        0  164.00          75     820   3893.0  2834.00